#PATHS
LINUX_OS_DIR ?= $(shell pwd)
OS_SOFTWARE_DIR=$(LINUX_OS_DIR)/software
OS_DIR=$(OS_SOFTWARE_DIR)/OS_build
OS_SUBMODULES_DIR=$(LINUX_OS_DIR)/submodules

#RISC-V HARD MULTIPLIER AND DIVIDER INSTRUCTIONS
USE_MUL_DIV ?=1

#RISC-V ATOMIC INSTRUCTIONS
USE_ATOMIC ?=1

#RISC-V COMPRESSED INSTRUCTIONS
USE_COMPRESSED ?=1
