name: CI

# Set default shell as interactive (source ~/.bashrc)
defaults:
  run:
    shell: bash -ieo pipefail {0}

# Run only one instance of this workflow at a time
# cancel-in-progress: stop running workflow and run latest instead
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
        - main
  # Don't forget to require approval for all outside collaborators
  pull_request:
    branches: '*'
  # Allow manual workflow runs
  workflow_dispatch:

jobs:
  minimal_OS:
    runs-on: self-hosted
    timeout-minutes: 30
    # run even if previous job failed
    if: ${{ !cancelled() }}
    # run after indicated job

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: clean-OS
        run: make clean-OS
      - name: test-dts
        run: nix-shell --run "make build-dts"
      - name: test-kernel
        run: nix-shell --run "make build-linux-kernel"
      - name: test-OpenSBI
        run: nix-shell --run "make build-opensbi"
