name: CI

# Set default shell as interactive (source ~/.bashrc)
defaults:
  run:
    shell: bash -ieo pipefail {0}

# Run only one instance of this workflow at a time
# cancel-in-progress: stop running workflow and run latest instead
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
        - main
  # Don't forget to require approval for all outside collaborators
  pull_request:
    branches: '*'
  # Allow manual workflow runs
  workflow_dispatch:

jobs:
  minimal_OS:
    runs-on: self-hosted
    timeout-minutes: 120
    # run even if previous job failed
    if: ${{ !cancelled() }}
    # run after indicated job

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: remove any old container or image (if exists)
        run: |
          docker stop gh_iob_linux_container || true
          docker rm gh_iob_linux_container || true
          docker rmi gh_iob_linux || true
      - name: build-container-image
        run: docker build --pull --rm -t gh_iob_linux "."
      - name: run-container
        run: docker run --name gh_iob_linux_container -dit gh_iob_linux
      - name: exec-container
        run: docker exec gh_iob_linux_container sh -c "make build-OS"
      - name: rm-container
        run: docker stop gh_iob_linux_container && docker rm gh_iob_linux_container
      - name: rm-image
        run: docker rmi gh_iob_linux
